### ISSUE TITLE
Serial code can return negative numbers on large input arrays

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-Systems/Threaded-minimum-pairwise-distance#3]
If you provide a large enough array of number (100K is pretty consistent) then you're likely to get `Integer.MIN_VALUE` as the result. This seems impossible since you're returning the absolute value of the difference of a pair of values. It turns out that this is because [a weird issue with Java and integer representation](http://stackoverflow.com/questions/5444611/math-abs-returns-wrong-value-for-integer-min-value).

Because of the asymmetry caused by the presence of 0 in the `int` type, `Integer.MIN_VALUE` (-2147483648) has magnitude one greater than `Integer.MAX_VALUE` (+2147483647). So if the difference of the two values is `Integer.MIN_VALUE`, then attempting to take its absolute value leads to a number that can't be represented as an `int` and you end up (due to the details of two's complement) flipping back to `Integer.MIN_VALUE`!

This is probably a very unlikely thing to ever run into, but if we have an array of 100K numbers, then we have 4,999,950,000 (just under 5 billion) pairs of values. That samples the just over 4 billion possible `int` values heavily enough that the odds of sampling that particular value gets pretty high. If/when it happens, we get this weird negative result.

There are several possible solutions:

* Change all the `int`s to `long`s except for those in the actual array. This is probably the preferable option.
* Mod all the values in the array to something like 1,000,000,000 to make sure that the difference can't ever be the Bad Thing. This is a hack, but it works.
* Check for that particular difference and convert it to something that doesn't blow up. That is definitely a hack, but again would work.

**Comment by NicMcPhee** [comment]
Closed by 008733d0b23e53ea794bf7fa855c1f9d3a534eda

I just changed the relevant `int`s to `longs since that seemed the simplest approach.

**Comment by deglm006** [comment]
Changing the int array into a long array seemed like it would be easier to understand than needing to cast the ints into longs in the MPD code before the subtraction. We need to still use random.nextInt() when generating a random array instead of random.nextLong, otherwise we get the same issue but with longs.

**Comment by NicMcPhee** [comment]
Finally got around to looking at this, and I'm not sure I'm convinced (but I'm also not sure I'm _not_ convinced).

I like having the arrays be `int`s because then we can't accidentally put `long`s in the array. If we were to end up with an array of `long`s, we end up with the same problem, just pushed down the road a bit. So my inclination is to leave the arrays as `int`s and only have the things that _have_ to be `long` be `long`.

I do agree, though, that this approach creates a potentially confusing need to cast from `int` to `long`, which is a bummer. Maybe that needs to be better documented?

Thoughts?

**Comment by NicMcPhee** [comment]
Actually, I think we should continue this discussion over in [your pull request](https://github.com/UMM-CSci-Systems/Threaded-minimum-pairwise-distance/pull/8#issuecomment-568288331). 😄
